CONVERT_TO = rp2040_ce

# this board has no per-key LEDs and no OLEDs
RGB_MATRIX_ENABLE = no
OLED_ENABLE = no

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
LAYER_LOCK_ENABLE = yes
SEND_STRING_ENABLE = yes

SRC += features/swapper.c

TAP_DANCE_ENABLE = no
# optimisations
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
