#pragma once

#define MASTER_LEFT

#define TAPPING_TERM 250

#define QUICK_TAP_TERM 100
#define QUICK_TAP_TERM_PER_KEY

#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define FLOW_TAP_TERM 100

#define ONESHOT_TIMEOUT 900

#define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 5000

#define COMBO_TERM 35
#define COMBO_STRICT_TIMER

#define CUSTOM_SHIFT_KEYS_NEGMODS ~MOD_MASK_SHIFT

#define LAYER_LOCK_IDLE_TIMEOUT 60000

#define UNICODE_SELECTED_MODES UNICODE_MODE_MACOS
