CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
LAYER_LOCK_ENABLE = yes
SEND_STRING_ENABLE = yes
TAP_DANCE_ENABLE = no
# RGBLIGHT_ENABLE = no
# RGB_MATRIX_ENABLE = no

SRC += features/swapper.c

# optimisations
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
